language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install: "pip install -r requirements.txt"
script:
  - python classify.py sql examples/feature_class.yml
  - python classify.py python examples/feature_class.yml
  - python classify.py javascript examples/feature_class.yml
